# Generated by Django 3.2.8 on 2021-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_customised',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
