# Generated by Django 3.2.8 on 2021-10-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_location_customised'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_movie',
            new_name='working_hours',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav_sport',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav_team',
        ),
    ]
